title: Cow-droid Github Page
author: cow-droid
email: cowmokjw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  Yes and I don't know what to write

# social links
twitter_username: cow # DO NOT include the @ character, or else the build will fail!
github_username:  cow-droid # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
